"""XML utility functions for LinkForge."""

import xml.etree.ElementTree as ET
from collections.abc import Callable
from datetime import datetime
from typing import Any

from ..exceptions import RobotMathError, RobotValidationError
from ..models import Vector3

# Register XACRO namespace to ensure standard 'xacro:' prefix in exports
ET.register_namespace("xacro", "http://www.ros.org/wiki/xacro")

MAX_XML_DEPTH = 100


def validate_xml_depth(element: ET.Element, depth: int = 0) -> None:
    """Validate XML depth to prevent billion laughs attack.

    Args:
        element: XML element to validate
        depth: Current nesting depth

    Raises:
        RobotValidationError: If depth exceeds MAX_XML_DEPTH
    """
    if depth > MAX_XML_DEPTH:
        raise RobotValidationError(check_name="XMLDepth", value=depth, reason="Nesting too deep")

    for child in element:
        validate_xml_depth(child, depth + 1)


def get_xml_header(element: ET.Element, version: str) -> str:
    """Standardized header comment for XML files.

    Args:
        element: Root XML element (to extract robot name)
        version: LinkForge version

    Returns:
        Header string containing XML declaration and meta comment
    """
    return f"""<?xml version="1.0"?>
<!--
  Robot: {element.get("name", "robot")}
  Generated by: LinkForge v{version}
  https://github.com/arounamounchili/linkforge
  Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
-->
"""


def indent_xml(element: ET.Element, space: str = "  ", level: int = 0) -> None:
    """Format XML elements with indentation.

    Args:
        element: XML element to indent
        space: Indentation string
        level: Starting level
    """
    ET.indent(element, space=space, level=level)


def serialize_xml(
    element: ET.Element,
    pretty_print: bool = True,
    version: str = "unknown",
    namespaces: dict[str, str] | None = None,
) -> str:
    """Convert XML element to standardized LinkForge string.

    Args:
        element: XML element to serialize
        pretty_print: Whether to indent
        version: LinkForge version for header
        namespaces: Optional dict of {prefix: uri} to register

    Returns:
        XML string
    """
    if namespaces:
        for prefix, uri in namespaces.items():
            ET.register_namespace(prefix, uri)

    if pretty_print:
        indent_xml(element)

    xml_str = ET.tostring(element, encoding="unicode")

    # Ensure namespaces are explicitly present on root if ElementTree dropped them
    if namespaces:
        for prefix, uri in namespaces.items():
            ns_attr = f'xmlns:{prefix}="{uri}"'
            if ns_attr not in xml_str and "<robot" in xml_str:
                xml_str = xml_str.replace("<robot", f"<robot {ns_attr}", 1)

    return get_xml_header(element, version) + xml_str


def parse_float(
    text: str | None,
    attribute_name: str = "value",
    default: float | None = None,
    check_name: str | None = None,
) -> float:
    """Parse float value from XML with comprehensive validation.

    Args:
        text: String to parse
        attribute_name: Context for error messages
        default: Default value if text is None
        check_name: Alias for attribute_name used in some parsers

    Returns:
        Parsed float

    Raises:
        RobotMathError: If input is invalid
        RobotValidationError: If attribute is missing
    """
    import math

    # Alias check_name if provided
    report_name = check_name or attribute_name

    if text is not None and not text.strip():
        text = None

    if text is None:
        if default is not None:
            return default
        raise RobotValidationError(check_name=report_name, reason="Missing required attribute")

    try:
        value = float(text)
        if math.isnan(value) or math.isinf(value):
            raise RobotMathError(value=value, check_name=report_name)

        # Sanity check for reasonable values (Standard LinkForge limit)
        if not (-1e10 < value < 1e10):
            raise RobotMathError(
                value=value, check_name=report_name, reason="outside reasonable range"
            )

        return value
    except ValueError:
        raise RobotMathError(value=text, check_name=report_name) from None


def parse_int(
    text: str | None,
    attribute_name: str = "value",
    default: int | None = None,
    check_name: str | None = None,
) -> int:
    """Parse integer value from XML with comprehensive validation.

    Args:
        text: String to parse
        attribute_name: Context for error messages
        default: Default value if text is None
        check_name: Alias for attribute_name for consistent reporting

    Returns:
        Parsed integer

    Raises:
        RobotMathError: If input format is invalid or value is out of range
        RobotValidationError: If attribute is missing and no default is provided
    """
    report_name = check_name or attribute_name

    if text is not None and not text.strip():
        text = None

    if text is None:
        if default is not None:
            return default
        raise RobotValidationError(check_name=report_name, reason="Missing required attribute")

    try:
        value = int(text)
        # Sanity check for reasonable values (standard LinkForge limit)
        if not (-1000000 < value < 1000000):
            raise RobotMathError(
                value=value, check_name=report_name, reason="outside reasonable range"
            )
        return value
    except ValueError:
        raise RobotMathError(value=text, check_name=report_name, reason="invalid format") from None


def parse_vector3(text: str) -> Vector3:
    """Parse space-separated vector3 string.

    Args:
        text: Space-separated string (e.g. "1.0 2.0 3.0")

    Returns:
        Vector3 model

    Raises:
        RobotValidationError: If vector format is invalid or components are missing
        RobotMathError: If component values are invalid
    """
    parts = text.strip().split()
    if len(parts) != 3:
        raise RobotValidationError(check_name="Vector3", value=text, reason="Expected 3 values")
    try:
        x = parse_float(parts[0], "x")
        y = parse_float(parts[1], "y")
        z = parse_float(parts[2], "z")
        return Vector3(x, y, z)
    except (RobotMathError, RobotValidationError):
        raise


def parse_optional_bool(elem: ET.Element, tag: str, default: str = "false") -> bool | None:
    """Parse optional boolean element.

    Args:
        elem: Parent XML element
        tag: Sub-element tag to find
        default: Default string value if tag is found but content is empty

    Returns:
        Boolean value if tag exists, else None
    """
    if elem.find(tag) is not None:
        return elem.findtext(tag, default).lower() == "true"
    return None


def parse_optional_float(elem: ET.Element, tag: str, default: float | None = 0.0) -> float | None:
    """Parse optional float element.

    Args:
        elem: Parent XML element
        tag: Sub-element tag to find
        default: Default float value if tag content is missing

    Returns:
        Parsed float if tag exists, else None

    Raises:
        RobotMathError: If input value is invalid or out of range
        RobotValidationError: If parsing logic fails
    """
    if elem.find(tag) is not None:
        text = elem.findtext(tag)
        return parse_float(text, tag, default=default)
    return None


def xml_add_text(parent: ET.Element, tag: str, value: Any) -> ET.Element:
    """Create a sub-element with text content.

    Args:
        parent: The parent XML element.
        tag: The tag name for the new element.
        value: The text content to set. Will be converted to string if not None.

    Returns:
        The newly created XML element.
    """
    elem = ET.SubElement(parent, tag)
    if value is not None:
        elem.text = str(value)
    return elem


def xml_add_vector(
    parent: ET.Element,
    tag: str,
    vector: Vector3,
    formatter: Callable[[float], str],
) -> ET.Element:
    """Create a sub-element for a vector relying on a formatter for the values.

    Args:
        parent: The parent XML element.
        tag: The tag name for the new element.
        vector: The Vector3 object containing the values.
        formatter: A callable that takes a float and returns a string (e.g., format_float).

    Returns:
        The newly created XML element with the formatted text string.
    """
    # Create text from formatted components
    text_val = f"{formatter(vector.x)} {formatter(vector.y)} {formatter(vector.z)}"
    return xml_add_text(parent, tag, text_val)


def create_xml_element(
    parent: ET.Element,
    tag: str,
    formatter: Callable[[Any], str] | None = None,
    **kwargs: Any,
) -> ET.Element:
    """Create an XML element, stripping None values and converting types to str.

    Args:
        parent: Parent XML element
        tag: Tag name for the new element
        formatter: Optional callable to format values before string conversion
        **kwargs: Attributes for the new element

    Returns:
        The newly created XML element
    """
    if formatter:
        attrib = {k: formatter(v) for k, v in kwargs.items() if v is not None}
    else:
        attrib = {k: str(v) for k, v in kwargs.items() if v is not None}
    return ET.SubElement(parent, tag, attrib)
